const ACTION_ON = "ON"
const ACTION_OFF = "OFF"

const MQTT_MESSAGE_GET_TELEMETRY = "GET_TELEMETRY"
const MQTT_MESSAGE_GET_DOOR_PASSWORD = "GET_DOOR_PASSWORD"
const MQTT_MESSAGE_HEALTH_CHECK = "ARE_YOU_OK"
const MQTT_MESSAGE_FIRE = "FIRE"
const MQTT_MESSAGE_FIRE_ACK = "FIRE_ACK"
const MQTT_MESSAGE_ONLINE = "ONLINE"

const ERROR_MQTT_NOT_CONNECTED = "MQTT_NOT_CONNECTED"
const ERROR_INVALID_ACTION = "INVALID_ACTION"
const ERROR_INVALID_INPUT = "INVALID_INPUT"

const DEFAULT_TEST_HOLD_MS = 2000
const DEFAULT_PORT = 3000
const MQTT_RECONNECT_PERIOD_MS = 2000
const MQTT_CONNECT_TIMEOUT_MS = 10000

module.exports = {
     ACTION_ON,
     ACTION_OFF,
     MQTT_MESSAGE_GET_TELEMETRY,
     MQTT_MESSAGE_GET_DOOR_PASSWORD,
     MQTT_MESSAGE_HEALTH_CHECK,
     MQTT_MESSAGE_FIRE,
     MQTT_MESSAGE_FIRE_ACK,
     MQTT_MESSAGE_ONLINE,
     ERROR_MQTT_NOT_CONNECTED,
     ERROR_INVALID_ACTION,
     ERROR_INVALID_INPUT,
     DEFAULT_TEST_HOLD_MS,
     DEFAULT_PORT,
     MQTT_RECONNECT_PERIOD_MS,
     MQTT_CONNECT_TIMEOUT_MS,
}
